@FlowFactorTodoAPI_HostAddress = http://localhost:5209/api
### Get all tasks
GET {{FlowFactorTodoAPI_HostAddress}}/tasks

### Add a new task
POST {{FlowFactorTodoAPI_HostAddress}}/tasks
Content-Type: application/json

{
    "title": "New Task (1)",
    "description": "This is the first task",
    "status": "À faire",
    "user": {
        "firstName": "Sigmund",
        "lastName": "Freud"
    }
}

### Update task status
PATCH {{FlowFactorTodoAPI_HostAddress}}/tasks/1
Content-Type: application/json

{
    "status": "En cours"
}